version: "3.7"
services:

  db:
    build: ./db-docker
    image: database
    # 13. This mount should stay
    volumes:
      - db-data:/var/lib/mysql
    # 13: this port needs to go
    ports:
      - "3306:3306"
    networks:
      - docker-network
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    build: ./redis-docker
    image: redis
    # 13: this port needs to go
    ports:
      - "6379"
    networks:
      - docker-network
    deploy:
      restart_policy:
        condition: on-failure

  django:
    build: ./django-docker
    image: django
    # 13. This mount needs to go
    volumes:
      - ./django-docker/djangoapp:/djangoapp
    # 13: this port needs to go
    ports:
      - "8000:8000"
    networks:
      - docker-network
    links:
      - "db:database"
      - "redis:redischat"
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  react:
    build: ./react-docker
    image: react
    # 13. This mount needs to go
    volumes:
      - ./react-docker/frontend:/app
    # 13: this port can stay
    ports:
      - "80:3000"
    networks:
      - docker-network
    links:
      - "django:webserver"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  docker-network:

volumes:
  db-data:
